header-y += tavarua.h

header-y += msm_camera.h
header-y += vcap_fmt.h
header-y += msm_isp.h
header-y += msm_gemini.h
header-y += linux_rawchip.h
header-y += msm_gestures.h
header-y += msm_mercury.h
header-y += linux_yushanii.h
